apiVersion: apps/v1
kind: Deployment
metadata:
  name: collabrain-backend-deployment
  namespace: collabrain  
  labels:
    app: collabrain-backend1
  annotations:
    timestamp: "{{ .Release.Time.Time.Format "20060102-150405" }}"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: collabrain-backend1
  template:
    metadata:
      labels:
        app: collabrain-backend1
    spec:
      containers:
      - name: collabrain-backend1-container
        image: siddh13/collabrainbackend1:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
