apiVersion: apps/v1
kind: Deployment
metadata:
  name: collabrain-backend-deployment
  namespace: collabrain  
  labels:
    app: collabrain-backend1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: collabrain-backend1
  template:
    metadata:
      labels:
        app: collabrain-backend1
    spec:
      containers:
      - name: collabrain-backend1-container
        image: siddh13/collabrainbackend1:latest
        ports:
        - containerPort: 8080
