apiVersion: apps/v1
kind: Deployment
metadata:
  name: collabrain-frontend-deployment
  namespace: collabrain  
  labels:
    app: collabrain-frontend
  annotations:
    timestamp: "{{  }}"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: collabrain-frontend
  template:
    metadata:
      labels:
        app: collabrain-frontend
    spec:
      containers:
      - name: collabrain-frontend-container
        image: siddh13/collabrainfrontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
