name: Build and Push Docker Image

on:
  push:
    branches:
      - workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      OCI_PEM: ${{ secrets.OCI_PEM }}
      OCI_CONFIG: ${{ secrets.OCI_CONFIG }}
      WEBSITE_URL: "https://cb1.cybertech13.eu.org"
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create /utils folder and add PEM files
      run: |
        mkdir -p ./backend/utils
        echo "$OCI_PEM" > ./backend/utils/OCI_PEM.pem
        echo "$OCI_CONFIG" > ./backend/utils/OCI_CONFIG

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Update Timestamp in Deployment File
      run: |
       TIMESTAMP=$(date +'%Y%m%d-%H%M%S')
       sed -i "s/timestamp: .*/timestamp: \"$TIMESTAMP\"/" ./backend/.kube/deployment.yaml

    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo -n "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

        # Buildx command to build for multiple platforms
        docker buildx create --use
        docker buildx inspect --bootstrap

        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --push \
          -t siddh13/collabrainbackend1:latest \
          -f ./backend/dockerfile ./backend

    - name: Set up kubectl
      uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
        version: 'v1.21.0'

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f ./backend/.kube/deployment.yaml
    
    - name: Wait for 10 seconds
      run: sleep 10

    - name: Ping Website to confirm deployment
      run: |
        curl -I --retry 5 --retry-delay 5 $WEBSITE_URL
