name: Build and Push Docker Image

on:
  push:
    branches:
      - workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    
    steps:
    - name: Print Environment Variables
      run: |
        env
    - name: Print Environment Variables
      run: |
        echo "DOCKER_USERNAME: $DOCKER_USERNAME"
        echo "DOCKER_PASSWORD: $DOCKER_PASSWORD"

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo -n "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

        ls

        # Buildx command to build for multiple platforms
        docker buildx create --use
        docker buildx inspect --bootstrap

        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --push \
          -t siddh13/collabrainbackend1:latest \
          -f ./backend/dockerfile ./backend

    - name: Set up kubectl
      uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
        version: 'v1.21.0'

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f ./backend/.kube/deployment.yaml
